name: cosmdart
description: A monorepo project containing multiple Dart packages.
version: 0.0.0
repository: https://github.com/yanglaolee/cosmdart

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
