name: chain_registry_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0

dev_dependencies:
  path: ^1.8.0
  lints: ^3.0.0
  test: ^1.24.0
