name: comet_clients
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  http: ^1.2.1
  convert: ^3.1.1
  web_socket_channel: ^3.0.0
  json_annotation: ^4.9.0  # # a package containing annotations for json_serializable
  freezed_annotation: ^2.4.4  # a package containing annotations for freezed
  synchronized: ^3.1.0+1
  cosmdart_types:
    git: 
      url: https://github.com/yanglaolee/cosmdart-types.git

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.11 # the tool to run code-generators
  json_serializable: ^6.8.0 # # the code generator
  freezed: ^2.5.7  # the code generator

